# Generated by Django 5.0.6 on 2024-11-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_bookimages_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimages',
            name='book',
            field=models.ForeignKey(blank=True, db_column='book_project_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.bookproject', to_field='book_id'),
        ),
    ]
