# Generated by Django 5.0.6 on 2024-08-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_bookproject_delete_book_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_url', models.CharField(blank=True, max_length=200, null=True)),
                ('book', models.ForeignKey(blank=True, db_column='book_project_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.bookproject')),
            ],
            options={
                'db_table': 'book_images',
                'managed': True,
            },
        ),
    ]
