# Generated by Django 5.0.6 on 2024-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_alter_bookimages_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimages',
            name='book',
        ),
        migrations.AddField(
            model_name='bookimages',
            name='book_id',
            field=models.CharField(blank=True, db_column='book_id', max_length=15, null=True),
        ),
    ]
