# Generated by Django 5.0.6 on 2024-11-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_remove_bookimages_book_bookimages_book_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookImages',
        ),
    ]
