# Generated by Django 5.1.3 on 2024-11-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_delete_bookimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookProject',
            new_name='BookCatalog',
        ),
        migrations.AlterModelTable(
            name='bookcatalog',
            table='book_catalog',
        ),
    ]
