# Generated by Django 5.1.3 on 2024-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_rename_bookproject_bookcatalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_pass', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'login_catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('user_pass', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'register_catalog',
                'managed': False,
            },
        ),
    ]
