# Generated by Django 5.1.3 on 2024-11-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_logincatalog_registercatalog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginCatalog',
        ),
        migrations.DeleteModel(
            name='RegisterCatalog',
        ),
    ]
