# Generated by Django 5.1.3 on 2024-11-29 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_rating_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.bookcatalog'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.bookcatalog'),
        ),
        migrations.AlterModelTable(
            name='rating',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
